[workspace]
resolver = "2"
members = [
    "crates/capsudo-proto",
    "crates/capsudo-transport",
    "crates/capsudo-core",
    "crates/capsudo",
    "crates/capsudod",
    "crates/capsudod-pwauth",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "0BSD"
authors = ["Edera, Inc."]
homepage = "https://github.com/edera-dev/capsudo-rs"
repository = "https://github.com/edera-dev/capsudo-rs"

[workspace.dependencies]
thiserror = "2"
async-trait = "0.1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "io-util", "macros", "sync", "time", "process", "signal"] }
nix = { version = "0.31", features = ["socket", "uio", "term", "process", "fs", "user", "hostname"] }
libc = "0.2"
capsudo-proto = { path = "crates/capsudo-proto", version = "0.1.0" }
capsudo-transport = { path = "crates/capsudo-transport", version = "0.1.0" }
capsudo-core = { path = "crates/capsudo-core", version = "0.1.0" }
